### ISSUE TITLE
How to support 1:1 communication between client and server using SSE

### ISSUE THREAD

**Issue by manishoswal** [mchaov/simple-sse-nodejs-setup#3]
What is the best way to support every browser request as an independent connection. 
For every requesting client we need to send client specific message to that client and not to all connected users.

Where should we save the each response object for the requesting client ?

**Comment by mchaov** [comment]
I am unaware if there is some ready examples published. There is no differences between how you handle this and websockets on the back-end.

Here: https://stackoverflow.com/questions/57323456/how-to-send-server-sent-event-notifications-when-needed-not-periodically-to-a/57324274 I tried helping to a guy with some explanation.

Basically you need to create your own structure and manage users. You can create a hashtable like:
```
{
    [key: userID]: ResponseObject
}
```
What type of structure you are going to use depends on your language and needs.
